
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GreatRune {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme gold;
        
        private Terminal.Gui.Window window;
        
        private Terminal.Gui.Button btnQuit;
        
        private Terminal.Gui.Label lblGodrick;
        
        private Terminal.Gui.Label lblMohg;
        
        private Terminal.Gui.Label lblRykard;
        
        private Terminal.Gui.Label lblMalenia;
        
        private Terminal.Gui.Label lblRadahn;
        
        private Terminal.Gui.Label lblRennala;
        
        private Terminal.Gui.Label lblMorgott;
        
        private Terminal.Gui.CheckBox chkAuto;
        
        private Terminal.Gui.Label lblStatus;
        
        private void InitializeComponent() {
            this.lblStatus = new Terminal.Gui.Label();
            this.chkAuto = new Terminal.Gui.CheckBox();
            this.lblMorgott = new Terminal.Gui.Label();
            this.lblRennala = new Terminal.Gui.Label();
            this.lblRadahn = new Terminal.Gui.Label();
            this.lblMalenia = new Terminal.Gui.Label();
            this.lblRykard = new Terminal.Gui.Label();
            this.lblMohg = new Terminal.Gui.Label();
            this.lblGodrick = new Terminal.Gui.Label();
            this.btnQuit = new Terminal.Gui.Button();
            this.window = new Terminal.Gui.Window();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.gold = new Terminal.Gui.ColorScheme();
            this.gold.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightYellow, Terminal.Gui.Color.Black);
            this.gold.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightYellow, Terminal.Gui.Color.Black);
            this.gold.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.gold.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.gold.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.BrightYellow);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.None;
            this.Border.BorderBrush = Terminal.Gui.Color.Gray;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.window.Width = 51;
            this.window.Height = 13;
            this.window.X = Pos.Center();
            this.window.Y = Pos.Center();
            this.window.Visible = true;
            this.window.ColorScheme = this.greyOnBlack;
            this.window.Modal = false;
            this.window.IsMdiContainer = false;
            this.window.Data = "window";
            this.window.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.window.Border.Effect3D = true;
            this.window.Border.Effect3DBrush = null;
            this.window.Border.DrawMarginFrame = true;
            this.window.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Title = "";
            this.Add(this.window);
            this.btnQuit.Width = 5;
            this.btnQuit.Height = 1;
            this.btnQuit.X = 43;
            this.btnQuit.Y = 0;
            this.btnQuit.Visible = true;
            this.btnQuit.ColorScheme = this.gold;
            this.btnQuit.Data = "btnQuit";
            this.btnQuit.Text = "X";
            this.btnQuit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnQuit.IsDefault = false;
            this.window.Add(this.btnQuit);
            this.lblGodrick.Width = 4;
            this.lblGodrick.Height = 1;
            this.lblGodrick.X = 2;
            this.lblGodrick.Y = 1;
            this.lblGodrick.Visible = true;
            this.lblGodrick.Data = "lblGodrick";
            this.lblGodrick.Text = "- Godrick\'s ";
            this.lblGodrick.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblGodrick);
            this.lblMohg.Width = 4;
            this.lblMohg.Height = 1;
            this.lblMohg.X = 19;
            this.lblMohg.Y = 1;
            this.lblMohg.Visible = true;
            this.lblMohg.Data = "lblMohg";
            this.lblMohg.Text = "- Mohg\'s ";
            this.lblMohg.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblMohg);
            this.lblRykard.Width = 4;
            this.lblRykard.Height = 1;
            this.lblRykard.X = 2;
            this.lblRykard.Y = 3;
            this.lblRykard.Visible = true;
            this.lblRykard.Data = "lblRykard";
            this.lblRykard.Text = "- Rykard\'s";
            this.lblRykard.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblRykard);
            this.lblMalenia.Width = 14;
            this.lblMalenia.Height = 1;
            this.lblMalenia.X = 19;
            this.lblMalenia.Y = 3;
            this.lblMalenia.Visible = true;
            this.lblMalenia.Data = "lblMalenia";
            this.lblMalenia.Text = "- Malania\'s";
            this.lblMalenia.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblMalenia);
            this.lblRadahn.Width = 4;
            this.lblRadahn.Height = 1;
            this.lblRadahn.X = 2;
            this.lblRadahn.Y = 5;
            this.lblRadahn.Visible = true;
            this.lblRadahn.Data = "lblRadahn";
            this.lblRadahn.Text = "- Radahn\'s";
            this.lblRadahn.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblRadahn);
            this.lblRennala.Width = 4;
            this.lblRennala.Height = 1;
            this.lblRennala.X = 19;
            this.lblRennala.Y = 5;
            this.lblRennala.Visible = true;
            this.lblRennala.ColorScheme = this.greyOnBlack;
            this.lblRennala.Data = "lblRennala";
            this.lblRennala.Text = "- Rennala\'s";
            this.lblRennala.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblRennala);
            this.lblMorgott.Width = 4;
            this.lblMorgott.Height = 1;
            this.lblMorgott.X = 2;
            this.lblMorgott.Y = 7;
            this.lblMorgott.Visible = true;
            this.lblMorgott.Data = "lblMorgott";
            this.lblMorgott.Text = "- Morgott\'s";
            this.lblMorgott.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblMorgott);
            this.chkAuto.Width = 6;
            this.chkAuto.Height = 1;
            this.chkAuto.X = 33;
            this.chkAuto.Y = 9;
            this.chkAuto.Visible = true;
            this.chkAuto.Data = "chkAuto";
            this.chkAuto.Text = "Auto-activate";
            this.chkAuto.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkAuto.Checked = false;
            this.window.Add(this.chkAuto);
            this.lblStatus.Width = 48;
            this.lblStatus.Height = 1;
            this.lblStatus.X = 0;
            this.lblStatus.Y = 10;
            this.lblStatus.Visible = true;
            this.lblStatus.ColorScheme = this.gold;
            this.lblStatus.Data = "lblStatus";
            this.lblStatus.Text = " Process not found";
            this.lblStatus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblStatus);
        }
    }
}
