
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GreatRune {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme gold;
        
        private Terminal.Gui.Window window;
        
        private Terminal.Gui.Button btnQuit;
        
        private Terminal.Gui.CheckBox chkGodrick;
        
        private Terminal.Gui.CheckBox chkMohg;
        
        private Terminal.Gui.CheckBox chkRykard;
        
        private Terminal.Gui.CheckBox chkMalenia;
        
        private Terminal.Gui.CheckBox chkRadahn;
        
        private Terminal.Gui.CheckBox chkRennala;
        
        private Terminal.Gui.CheckBox chkMorgott;
        
        private Terminal.Gui.CheckBox chkAuto;
        
        private Terminal.Gui.Label lblStatus;
        
        private void InitializeComponent() {
            this.lblStatus = new Terminal.Gui.Label();
            this.chkAuto = new Terminal.Gui.CheckBox();
            this.chkMorgott = new Terminal.Gui.CheckBox();
            this.chkRennala = new Terminal.Gui.CheckBox();
            this.chkRadahn = new Terminal.Gui.CheckBox();
            this.chkMalenia = new Terminal.Gui.CheckBox();
            this.chkRykard = new Terminal.Gui.CheckBox();
            this.chkMohg = new Terminal.Gui.CheckBox();
            this.chkGodrick = new Terminal.Gui.CheckBox();
            this.btnQuit = new Terminal.Gui.Button();
            this.window = new Terminal.Gui.Window();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.gold = new Terminal.Gui.ColorScheme();
            this.gold.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.BrightYellow);
            this.gold.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightYellow, Terminal.Gui.Color.Black);
            this.gold.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.gold.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.gold.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightYellow, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.None;
            this.Border.BorderBrush = Terminal.Gui.Color.Gray;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.window.Width = 51;
            this.window.Height = 13;
            this.window.X = Pos.Center();
            this.window.Y = Pos.Center();
            this.window.Visible = true;
            this.window.ColorScheme = this.greyOnBlack;
            this.window.Modal = false;
            this.window.IsMdiContainer = false;
            this.window.Data = "window";
            this.window.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.window.Border.Effect3D = true;
            this.window.Border.Effect3DBrush = null;
            this.window.Border.DrawMarginFrame = true;
            this.window.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Title = "";
            this.Add(this.window);
            this.btnQuit.Width = 5;
            this.btnQuit.Height = 1;
            this.btnQuit.X = 43;
            this.btnQuit.Y = 0;
            this.btnQuit.Visible = true;
            this.btnQuit.Data = "btnQuit";
            this.btnQuit.Text = "X";
            this.btnQuit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnQuit.IsDefault = false;
            this.window.Add(this.btnQuit);
            this.chkGodrick.Width = 6;
            this.chkGodrick.Height = 1;
            this.chkGodrick.X = 2;
            this.chkGodrick.Y = 1;
            this.chkGodrick.Visible = true;
            this.chkGodrick.Data = "chkGodrick";
            this.chkGodrick.Text = "Godrick\'s";
            this.chkGodrick.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkGodrick.Checked = false;
            this.window.Add(this.chkGodrick);
            this.chkMohg.Width = 6;
            this.chkMohg.Height = 1;
            this.chkMohg.X = 19;
            this.chkMohg.Y = 1;
            this.chkMohg.Visible = true;
            this.chkMohg.Data = "chkMohg";
            this.chkMohg.Text = "Mohg\'s";
            this.chkMohg.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkMohg.Checked = false;
            this.window.Add(this.chkMohg);
            this.chkRykard.Width = 6;
            this.chkRykard.Height = 1;
            this.chkRykard.X = 2;
            this.chkRykard.Y = 3;
            this.chkRykard.Visible = true;
            this.chkRykard.Data = "chkRykard";
            this.chkRykard.Text = "Rykard\'s";
            this.chkRykard.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkRykard.Checked = false;
            this.window.Add(this.chkRykard);
            this.chkMalenia.Width = 11;
            this.chkMalenia.Height = 1;
            this.chkMalenia.X = 19;
            this.chkMalenia.Y = 3;
            this.chkMalenia.Visible = true;
            this.chkMalenia.Data = "chkMalenia";
            this.chkMalenia.Text = "Malenia\'s";
            this.chkMalenia.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkMalenia.Checked = false;
            this.window.Add(this.chkMalenia);
            this.chkRadahn.Width = 6;
            this.chkRadahn.Height = 1;
            this.chkRadahn.X = 2;
            this.chkRadahn.Y = 5;
            this.chkRadahn.Visible = true;
            this.chkRadahn.Data = "chkRadahn";
            this.chkRadahn.Text = "Radahn\'s";
            this.chkRadahn.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkRadahn.Checked = false;
            this.window.Add(this.chkRadahn);
            this.chkRennala.Width = 10;
            this.chkRennala.Height = 1;
            this.chkRennala.X = 19;
            this.chkRennala.Y = 5;
            this.chkRennala.Visible = true;
            this.chkRennala.Data = "chkRennala";
            this.chkRennala.Text = "Rennala\'s";
            this.chkRennala.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkRennala.Checked = false;
            this.window.Add(this.chkRennala);
            this.chkMorgott.Width = 6;
            this.chkMorgott.Height = 1;
            this.chkMorgott.X = 2;
            this.chkMorgott.Y = 7;
            this.chkMorgott.Visible = true;
            this.chkMorgott.Data = "chkMorgott";
            this.chkMorgott.Text = "Morgott\'s";
            this.chkMorgott.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkMorgott.Checked = false;
            this.window.Add(this.chkMorgott);
            this.chkAuto.Width = 6;
            this.chkAuto.Height = 1;
            this.chkAuto.X = 33;
            this.chkAuto.Y = 9;
            this.chkAuto.Visible = true;
            this.chkAuto.Data = "chkAuto";
            this.chkAuto.Text = "Auto-activate";
            this.chkAuto.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkAuto.Checked = false;
            this.window.Add(this.chkAuto);
            this.lblStatus.Width = Dim.Fill(0);
            this.lblStatus.Height = 1;
            this.lblStatus.X = 0;
            this.lblStatus.Y = 10;
            this.lblStatus.Visible = true;
            this.lblStatus.ColorScheme = this.gold;
            this.lblStatus.Data = "lblStatus";
            this.lblStatus.Text = " Process not found";
            this.lblStatus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.lblStatus);
        }
    }
}
